language: python
python:
  - "2.7"

install:
  - sudo apt-get install libdb5.3-dev
  - pip install -r requirements.txt --use-mirrors
  - pip install -e .

before_script: python fcs/manage.py syncdb --noinput
script: coverage run --source fcs/fcs -m py.test

after_success:
  - coveralls
