language: python
python:
  - "2.7"

install:
  - wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
  - tar -xzvf db-4.8.30.NC.tar.gz
  - cd db-4.8.30.NC/build_unix
  - ../dist/configure --enable-cxx
  - make
  - sudo make install
  - cd ../..
  - export BDB_INCLUDE_PATH="/usr/local/BerkeleyDB.4.8/include"
  - export BDB_LIB_PATH="/usr/local/BerkeleyDB.4.8/lib"
  - pip install bsddb3
  - pip install -r requirements.txt --use-mirrors
  - pip install -e .

before_script: python fcs/manage.py syncdb --noinput
script: coverage run --source fcs/fcs -m py.test

after_success:
  - coveralls
