language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -e .

script:
  python fcs/manage.py syncdb
  coverage run --source fcs/fcs/manager -m py.test

after_success:
  - coveralls
